version: "3"
services:
  nats:
    image: nats-streaming
    ports:
      - 4222:4222
      - 8222:8222
    entrypoint: /nats-streaming-server
  read:
    image: node
    volumes:
    - ./:/app
    working_dir: /app/packages/read
    entrypoint: yarn run run
    depends_on:
      - nats
  write:
    image: node
    volumes:
      - ./:/app
    working_dir: /app/packages/write
    entrypoint: yarn run run
    depends_on:
      - nats
